import './style.css';
import { DeleteAgenda, HideWindow, ListAgendas, SaveAgenda, TestAlarmSound } from '../wailsjs/go/main/App';
import { EventsOn } from '../wailsjs/runtime/runtime';
import type { model } from '../wailsjs/go/models';

type Agenda = model.Agenda;
const state = { selectedDate: dayStart(new Date()), days: 3, agendas: [] as Agenda[], editing: null as Agenda | null };
const app = document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML = `
<div class="shell">
 <aside><div class="brand"><b>R</b><span><strong>ReCall</strong><small>Agenda & pengingat</small></span></div>
 <button class="primary wide" id="new">＋ Agenda baru</button>
 <section class="mini"><header><button id="mp">‹</button><strong id="ml"></strong><button id="mn">›</button></header><div class="week"><i>Sn</i><i>Sl</i><i>Rb</i><i>Km</i><i>Jm</i><i>Sb</i><i>Mg</i></div><div class="month" id="month"></div></section>
 <div class="legend"><span><i class="blue"></i>Kegiatan</span><span><i class="violet"></i>Pribadi</span><span><i class="green"></i>Fokus</span></div>
 <div class="tray"><b>◉</b><span><strong>Aktif di background</strong><small>Tutup jendela untuk sembunyikan ke tray.</small><button id="test-sound">Uji suara alarm</button></span></div></aside>
 <main><header class="toolbar"><div class="nav"><button class="secondary" id="today">Hari ini</button><button class="icon bordered" id="prev">‹</button><button class="icon bordered" id="next">›</button><span><h1 id="range"></h1><small id="count"></small></span></div><div class="actions"><div class="switch"><button data-days="1">Hari</button><button data-days="3" class="active">3 Hari</button><button data-days="7">Minggu</button></div><button class="icon bordered" id="hide">—</button></div></header>
 <section class="calendar-scroll"><div class="calendar" id="calendar"></div></section></main>
</div>
<div class="backdrop hidden" id="editor"><div class="modal"><header><span><p>Jadwal kegiatan</p><h2 id="form-title">Agenda baru</h2></span><button class="icon" data-close>×</button></header><form id="form">
 <label>Judul<input id="title" maxlength="120" required placeholder="Contoh: Rapat mingguan"></label><label>Catatan<textarea id="description" maxlength="2000" rows="3" placeholder="Tambahkan detail kegiatan"></textarea></label>
 <div class="form-grid"><label>Tanggal<input id="date" type="date" required></label><label>Waktu mulai<input id="start" type="time" required></label><label>Waktu selesai<input id="end" type="time" required></label></div>
 <div class="form-grid two"><label>Warna<select id="color"><option value="blue">Biru</option><option value="violet">Ungu</option><option value="green">Hijau</option><option value="amber">Kuning</option><option value="rose">Merah</option></select></label><label>Pengingat<select id="offset"><option value="0">Saat dimulai</option><option value="5">5 menit sebelumnya</option><option value="10">10 menit sebelumnya</option><option value="30">30 menit sebelumnya</option><option value="60">1 jam sebelumnya</option><option value="1440">1 hari sebelumnya</option></select></label></div>
 <label class="check"><input id="alarm" type="checkbox" checked>Aktifkan alarm untuk agenda ini</label><footer><button type="button" class="danger ghost hidden" id="delete">Hapus</button><i></i><button type="button" class="secondary" data-close>Batal</button><button class="primary" id="save">Simpan agenda</button></footer>
</form></div></div>
<div class="backdrop hidden" id="confirm"><div class="modal compact"><h2>Hapus agenda?</h2><p>Agenda ini akan dihapus permanen dari kalender.</p><footer><i></i><button class="secondary" id="cancel-delete">Batal</button><button class="danger" id="confirm-delete">Ya, hapus</button></footer></div></div>
<div class="backdrop hidden" id="alarm-modal"><div class="modal alarm"><div>⏰</div><p>Pengingat agenda</p><h2 id="alarm-title"></h2><span id="alarm-detail"></span><button class="primary wide" id="dismiss">Saya mengerti</button></div></div>
<div class="toasts" id="toasts"></div>`;

const $ = <T extends HTMLElement>(s: string) => document.querySelector<T>(s)!;
const value = (s: string) => ($<HTMLInputElement>(s).value);
function dayStart(v: Date) { const d=new Date(v); d.setHours(0,0,0,0); return d }
function addDays(v: Date,n:number){const d=new Date(v);d.setDate(d.getDate()+n);return d}
function key(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function iso(d:Date){const o=d.getTimezoneOffset(),s=o<=0?'+':'-',n=Math.abs(o);return new Date(d.getTime()-o*60000).toISOString().slice(0,-1)+`${s}${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function fmt(d:Date,o:Intl.DateTimeFormatOptions){return new Intl.DateTimeFormat('id-ID',o).format(d)}
function esc(s:string){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
async function load(){try{state.agendas=await ListAgendas(iso(state.selectedDate),iso(addDays(state.selectedDate,state.days)));render()}catch(e){toast(String(e),'error')}}
function render(){renderMonth();renderCalendar();document.querySelectorAll<HTMLButtonElement>('[data-days]').forEach(b=>b.classList.toggle('active',Number(b.dataset.days)===state.days))}
function renderMonth(){const b=state.selectedDate,f=new Date(b.getFullYear(),b.getMonth(),1),start=addDays(f,-((f.getDay()+6)%7));$('#ml').textContent=fmt(b,{month:'long',year:'numeric'});$('#month').innerHTML=Array.from({length:42},(_,i)=>{const d=addDays(start,i),c=[d.getMonth()!==b.getMonth()?'muted':'',key(d)===key(new Date())?'today':'',key(d)===key(b)?'selected':''].join(' ');return `<button class="${c}" data-date="${key(d)}">${d.getDate()}</button>`}).join('')}
function renderCalendar(){const days=Array.from({length:state.days},(_,i)=>addDays(state.selectedDate,i)),last=days.at(-1)!;$('#range').textContent=state.days===1?fmt(days[0],{weekday:'long',day:'numeric',month:'long'}):`${days[0].getDate()}–${fmt(last,{day:'numeric',month:'long',year:'numeric'})}`;$('#count').textContent=`${state.agendas.length} agenda pada rentang ini`;const hours=Array.from({length:24},(_,i)=>i),cal=$('#calendar');cal.style.setProperty('--days',String(state.days));cal.dataset.days=String(state.days);cal.innerHTML=`<div class="corner"></div>${days.map(d=>`<div class="day-head ${key(d)===key(new Date())?'is-today':''}"><span>${fmt(d,{weekday:'short'})}</span><b>${d.getDate()}</b></div>`).join('')}<div class="times">${hours.map(h=>`<div>${String(h).padStart(2,'0')}:00</div>`).join('')}</div>${days.map(d=>`<div class="day-col" data-date="${key(d)}">${hours.map(h=>`<div class="slot" data-hour="${h}"></div>`).join('')}${blocks(d)}${key(d)===key(new Date())?nowLine():''}</div>`).join('')}`}
function blocks(day:Date){return state.agendas.filter(a=>key(new Date(a.startAt))===key(day)).map(a=>{const s=new Date(a.startAt),e=new Date(a.endAt),top=(s.getHours()*60+s.getMinutes())/60*64,height=Math.max(34,(e.getTime()-s.getTime())/3600000*64-4);return `<button class="agenda-card ${a.color}" data-id="${a.id}" style="top:${top}px;height:${height}px"><b>${esc(a.title)}</b><span>${s.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}–${e.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}</span>${a.alarm?'<i>◉</i>':''}</button>`}).join('')}
function nowLine(){const n=new Date(),top=(n.getHours()*60+n.getMinutes())/60*64;return `<div class="now" style="top:${top}px"><i></i></div>`}
function openEditor(a?:Agenda,date?:Date,h=9){state.editing=a??null;const s=a?new Date(a.startAt):new Date(date??state.selectedDate);if(!a)s.setHours(h,0,0,0);const e=a?new Date(a.endAt):new Date(s.getTime()+3600000);$('#form-title').textContent=a?'Ubah agenda':'Agenda baru';$<HTMLInputElement>('#title').value=a?.title??'';$<HTMLTextAreaElement>('#description').value=a?.description??'';$<HTMLInputElement>('#date').value=key(s);$<HTMLInputElement>('#start').value=`${String(s.getHours()).padStart(2,'0')}:${String(s.getMinutes()).padStart(2,'0')}`;$<HTMLInputElement>('#end').value=`${String(e.getHours()).padStart(2,'0')}:${String(e.getMinutes()).padStart(2,'0')}`;$<HTMLSelectElement>('#color').value=a?.color??'blue';$<HTMLInputElement>('#alarm').checked=a?.alarm??true;$<HTMLSelectElement>('#offset').value=String(a?.alarmOffset??10);$('#delete').classList.toggle('hidden',!a);$('#editor').classList.remove('hidden');setTimeout(()=>$<HTMLInputElement>('#title').focus(),50)}
function close(){ $('#editor').classList.add('hidden') }
$<HTMLFormElement>('#form').addEventListener('submit',async e=>{e.preventDefault();const d=value('#date'),s=new Date(`${d}T${value('#start')}:00`),end=new Date(`${d}T${value('#end')}:00`),btn=$<HTMLButtonElement>('#save');btn.disabled=true;try{await SaveAgenda({id:state.editing?.id??0,title:value('#title'),description:value('#description'),startAt:iso(s),endAt:iso(end),color:value('#color'),alarm:$<HTMLInputElement>('#alarm').checked,alarmOffset:Number(value('#offset')),notifiedAt:'',createdAt:state.editing?.createdAt??'',updatedAt:state.editing?.updatedAt??''});close();toast(state.editing?'Agenda berhasil diperbarui.':'Agenda berhasil dibuat.','success');await load()}catch(x){toast(String(x),'error')}finally{btn.disabled=false}});
$('#new').onclick=()=>openEditor();document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',close));$('#today').onclick=()=>{state.selectedDate=dayStart(new Date());load()};$('#prev').onclick=()=>{state.selectedDate=addDays(state.selectedDate,-state.days);load()};$('#next').onclick=()=>{state.selectedDate=addDays(state.selectedDate,state.days);load()};$('#mp').onclick=()=>{state.selectedDate=new Date(state.selectedDate.getFullYear(),state.selectedDate.getMonth()-1,state.selectedDate.getDate());load()};$('#mn').onclick=()=>{state.selectedDate=new Date(state.selectedDate.getFullYear(),state.selectedDate.getMonth()+1,state.selectedDate.getDate());load()};$('#hide').onclick=()=>HideWindow();document.querySelectorAll<HTMLButtonElement>('[data-days]').forEach(b=>b.onclick=()=>{state.days=Number(b.dataset.days);load()});
$('#test-sound').onclick=async()=>{const b=$<HTMLButtonElement>('#test-sound');b.disabled=true;try{await TestAlarmSound();toast('Suara alarm berhasil diputar.','success')}catch(e){toast(String(e),'error')}finally{b.disabled=false}};
$('#month').onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-date]');if(b){state.selectedDate=dayStart(new Date(`${b.dataset.date}T00:00:00`));load()}};
$('#calendar').onclick=e=>{const card=(e.target as HTMLElement).closest<HTMLButtonElement>('.agenda-card');if(card){const a=state.agendas.find(x=>x.id===Number(card.dataset.id));if(a)openEditor(a);return}const slot=(e.target as HTMLElement).closest<HTMLElement>('.slot'),col=(e.target as HTMLElement).closest<HTMLElement>('.day-col');if(slot&&col)openEditor(undefined,new Date(`${col.dataset.date}T00:00:00`),Number(slot.dataset.hour))};
$('#delete').onclick=()=>$('#confirm').classList.remove('hidden');$('#cancel-delete').onclick=()=>$('#confirm').classList.add('hidden');$('#confirm-delete').onclick=async()=>{if(!state.editing)return;try{await DeleteAgenda(state.editing.id);$('#confirm').classList.add('hidden');close();toast('Agenda berhasil dihapus.','success');await load()}catch(e){toast(String(e),'error')}};
$('#dismiss').onclick=()=>$('#alarm-modal').classList.add('hidden');EventsOn('agenda:alarm',(a:Agenda)=>{$('#alarm-title').textContent=a.title;$('#alarm-detail').textContent=`${new Date(a.startAt).toLocaleString('id-ID',{weekday:'long',hour:'2-digit',minute:'2-digit'})}${a.description?` — ${a.description}`:''}`;$('#alarm-modal').classList.remove('hidden')});EventsOn('agenda:changed',load);
function toast(m:string,k:'success'|'error'){const e=document.createElement('div');e.className=`toast ${k}`;e.textContent=m.replace(/^Error:\s*/,'');$('#toasts').append(e);setTimeout(()=>e.remove(),4200)}
load();setInterval(renderCalendar,60000);
