// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAgenda(arg1) {
  return window['go']['main']['App']['DeleteAgenda'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ListAgendas(arg1, arg2) {
  return window['go']['main']['App']['ListAgendas'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveAgenda(arg1) {
  return window['go']['main']['App']['SaveAgenda'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
