// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteAgenda(arg1:number):Promise<void>;

export function HideWindow():Promise<void>;

export function ListAgendas(arg1:string,arg2:string):Promise<Array<model.Agenda>>;

export function Quit():Promise<void>;

export function SaveAgenda(arg1:model.Agenda):Promise<model.Agenda>;

export function ShowWindow():Promise<void>;

export function TestAlarmSound():Promise<void>;
